### ISSUE TITLE
Jeckle::API intermittent spec on jruby and rbx build

### ISSUE THREAD

**Issue by mateusg** [tomas-stefano/jeckle#55]
When running the examples on jruby or rbx, sometimes I get an error on `Jeckle::API#connection` spec:
```
Failures:

  1) Jeckle::API#connection assigns timeout options
     Failure/Error: expect(jeckle_api.connection.options.open_timeout).to eq 2
       
       expected: 2
            got: nil
       
       (compared using ==)
     # ./spec/lib/jeckle/api_spec.rb:37:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/common/kernel.rb:498:in `load'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:656:in `script'
     # kernel/loader.rb:810:in `main'

Finished in 0.7139 seconds (files took 2.07 seconds to load)
83 examples, 1 failure

Failed examples:

rspec ./spec/lib/jeckle/api_spec.rb:36 # Jeckle::API#connection assigns timeout options

Randomized with seed 40473
```

It also happens with seed 26503. I think it has something to do with Faraday.

**Comment by mateusg** [comment]
@brennovich

**Comment by mateusg** [comment]
It is failing on 2.0.0 too. :(
https://travis-ci.org/tomas-stefano/jeckle/jobs/63906860

**Comment by brennovich** [comment]
Huummm So it's failing on specific seeds... I'll investigate this ;)

**Comment by tomas-stefano** [comment]
This are the options.

[1] pry(#<RSpec::ExampleGroups::JeckleAPI::Connection>)> jeckle_api.connection.options
=> #<struct Faraday::RequestOptions params_encoder=nil, proxy=nil, bind=nil, timeout=nil, open_timeout=nil, boundary=nil, oauth=nil>

I think we can solve if the test was different. Is the test suppose to be asserting what options exactly contain inside Faraday?
